// Hover tooltips for the dev-panel sliders, keyed by the bound PROPERTY name (not the label).
// GameScene._applyTooltips walks every panel's controllers and sets the native `title` from this
// map, so one entry covers that property everywhere it appears. Each line: a technical description
// then a short "raise/lower to …" in plain terms. Properties not listed simply get no tooltip.
export const TOOLTIPS = {
  // ── Player / Vehicle handling ───────────────────────────────────────────────
  maxSpeed: "Top forward speed (px/s) before drag. Hard ceiling on velocity. Raise to go faster.",
  acceleration: "Throttle force (px/s²) added along the nose while accelerating. Raise for quicker pickup.",
  hardBrakeForce: "Deceleration from the dedicated brake (Shift). Raise for stronger braking.",
  brakeForce: "Deceleration when pressing Down while rolling forward. Raise for a stronger down-brake.",
  reverseAccel: "Acceleration while reversing. Raise to back up faster.",
  maxReverseSpeed: "Top reverse speed (px/s). Raise to reverse faster.",
  turnSpeedLow: "Yaw rate (rad/s) at low speed. Raise to turn sharper when slow.",
  turnSpeed: "Yaw rate (rad/s) at high speed, on throttle. Raise to turn sharper at speed (less planted).",
  turnSpeedHandbrake: "Yaw rate at high speed WHILE handbraking. Raise to whip the nose around harder in a drift.",
  maxDriftAngle: "Max angle (rad) the nose may deviate from velocity during a handbrake. Raise to allow wider slides.",
  pivotOffset: "Distance behind centre (px) the car rotates about while steering. Raise so the nose leads the turn (less floaty); 0 = spins about its centre.",
  minSteerFactor: "Floor on steering authority at low speed (0–1). Raise so a car can always rotate (deadlock-proof). Player = 0.",
  accelDragBase: "Per-frame drag while on throttle (nearer 1 = less drag). Lower to bleed speed faster.",
  accelDragCurve: "Extra drag at high speed (subtracted as speed²). Raise to lower the real top speed.",
  coastDrag: "Per-frame drag while coasting (no throttle/brake). Lower to coast to a stop faster.",
  handBrakeDrag: "Per-frame drag during a handbrake. Lower to scrub speed harder mid-drift.",
  gripLow: "Grip near zero speed (fraction velocity snaps toward the nose each frame). Raise to bite harder when slow.",
  gripHigh: "Grip at high speed (reached at gripSpeedRef). Raise to bite at speed — the main 'less floaty/drifty' dial.",
  gripSpeedRef: "Speed (px/s) at which grip reaches gripHigh. Raise to stay grippy across more of your speed range.",
  gripHandbrake: "Grip during a handbrake (very low = big slide). Lower for a looser drift.",
  entryKick: "Rotation (rad) snapped into the rear when a handbrake drift starts. Raise for a snappier drift initiation.",
  entryKickDuration: "Seconds the entry-kick eases in over. Raise for a slower kick.",
  entryKickCooldown: "Seconds before another entry kick can fire. Raise to space out drift starts.",
  playerCapR: "Player capsule radius (≈ half the car width) for the rotated-car collider. Raise to make the player wider in collisions.",
  playerCapHalfLen: "Player capsule half-length — front/rear collision circle offset. Raise to make the player longer in collisions.",

  // ── Capsule solver + ram-impact (swarm feel) ────────────────────────────────
  capIters: "Collision-solver iterations per frame. Raise to kill jitter and make a swarm contain you harder (costs a little perf).",
  capSlop: "Penetration (px) left uncorrected each frame. Raise to reduce micro-jitter at the cost of slight overlap.",
  capRelax: "Fraction of penetration corrected per iteration. Lower for smoother (less poppy) separation.",
  capFriction: "Tangential grip at car↔car contacts (0–1). Raise to make a swarm sticky — harder to slide out the seam.",
  playerMass: "Player weight in capsule collisions. Raise to shove cops aside more easily.",
  ramSpeedKill: "Max fraction of YOUR speed a full frontal cop ram removes. Raise to make head-on cop hits slow you more.",
  ramBogTime: "Seconds your engine is bogged after a hard frontal ram. Raise to make rams cost more recovery time.",
  ramBogAccel: "Engine power multiplier while bogged. Lower to make recovering from a ram harder.",
  ramRefSpeed: "Closing speed (px/s) counted as a full-strength frontal ram. Lower so slower hits count as full rams.",
  ramMinClosing: "Min closing speed for a frontal ram to register at all. Raise so only fast head-ons bog you.",

  // ── Ram damage / cop health / disabling ─────────────────────────────────────
  ramThreshold: "Closing speed (px/s) below which YOUR ram does no cop damage. Raise to make cops harder to ram-disable.",
  ramScale: "Cop damage per px/s of impact above the threshold. Raise to disable cops in fewer rams.",
  ramContactDist: "(Legacy) centre distance that counted as a hit; damage now fires from the real capsule contact. Mostly inert.",
  ramDmgCooldown: "Seconds between damage ticks on one cop. Raise so a single ram = one hit (less rapid chipping).",
  selfImpactDrop: "Sudden speed loss (px/s) in a frame that counts as a cop SELF-crash. Raise to make crash damage harder to trigger.",
  selfScale: "Cop self-damage per px/s of crash (aggressive cops only). Lower so cops survive their own crashes.",
  copCopRamThreshold: "Closing speed a cop↔cop (or cop↔roadblock) crash needs to deal damage. Raise so only hard wrecks hurt cops — less friendly fire.",
  copCopRamMult: "Cop↔cop damage as a fraction of base ram damage. Lower (or 0) so cops barely hurt each other.",
  wreckDespawn: "Seconds a disabled wreck stays as an obstacle. Raise to leave wrecks around longer.",
  wreckMass: "Disabled cop body weight. Lower to shove wrecks aside more easily.",
  disableReinforceMult: "Fraction of the normal reinforcement interval to wait after YOU disable a cop (capped — never slower). Lower = the gap refills faster so disabling doesn't thin the pack into an easy ditch.",
  copHealthPerLevel: "Extra fraction of base health per pursuit level above 1 (heat buff). Raise to make the pack tankier as heat rises.",
  health: "Damage this unit type soaks before it's disabled. Raise to make it tankier.",
  mass: "Unit weight — ram exchange, shove resistance, and damage division. Raise to make it shove harder and take less ram damage.",
  ramStrength: "How hard THIS unit's frontal ram hits YOUR momentum. Raise to make its head-ons more punishing.",

  // ── Roadblocks ──────────────────────────────────────────────────────────────
  roadblockDist: "Distance ahead (px) a roadblock is placed. Raise to place blocks further ahead.",
  roadblockInterval: "Seconds between auto-spawned roadblocks in pursuit. Lower for more frequent blocks.",
  maxActiveRoadblocks: "Max number of auto-spawned roadblocks allowed at once. Raise to allow double-stacking; 1 prevents two blocks overlapping at nearby intersections.",
  rbCarMass: "A roadblock car's shove weight. Raise to make it harder to push through.",
  rbHeavyMass: "A roadblock heavy's shove weight. Raise to make it harder to push through.",
  rbCarDrag: "Drag on a shoved roadblock car. Raise so shoved cars settle (stop sliding) faster.",
  rbLifetime: "Seconds a placed block lasts before despawning. Raise to leave blocks up longer.",
  rbSpinFactor: "Off-centre-hit → spin impulse on a block car. Raise so block cars spin out of the way more when clipped off-centre.",
  rbDamageMult: "Ram-through damage multiplier for block cars (toughness comes from their health, not shove mass). Raise to clear them in fewer rams.",
  rbSpikeChance: "Chance a non-anchor roadblock slot is a spike strip (difficulty 3+). Raise for more spike strips in blocks.",

  // ── Pursuit levels (heat + per-level) ───────────────────────────────────────
  activeRate: "Heat gained per second while actively chased. Raise to escalate levels faster.",
  ramHeat: "Heat added per player↔cop contact. Raise so ramming heats you up more.",
  heatFloor: "Minimum heat — never bleeds below this. Raise to stay partly hot after escaping.",
  fastFrac: "Fraction of a level's span shed at the FAST bleed rate. Raise to drop heat quickly right after escaping.",
  fastRate: "Fast bleed rate (heat/s) right after escaping. Raise to cool down faster initially.",
  slowRate: "Slow bleed rate once the fast portion is shed. Raise so you keep cooling instead of plateauing hot.",
  span: "Seconds of active chase to escalate to the next level. Raise to make this level last longer.",
  cap: "Max chasing cops at this level. Raise for more cops on screen.",
  reinforce: "Seconds between reinforcement spawns. Lower to fill the cop cap faster.",
  cooldown: "Seconds of lost line-of-sight before the chase ends at this level. Raise to make ditching harder.",
  reaction: "Cop reaction lag (s) at this level. Lower to make cops sharper/quicker.",
  boxTrigger: "Player speed below which cops set up a box at this level. Raise to make them box you more readily.",
  disableHeat: "Heat spike when YOU disable a cop. Raise to punish disabling (it heats you up).",

  // ── Maneuvers: drafting / overtake / block / box ────────────────────────────
  draftMinSpeed: "Player speed above which a fast cop drafts instead of grinding your bumper. Lower so cops draft sooner.",
  draftGap: "Distance (px) a drafting cop settles behind you. Raise so it tails from further back.",
  draftMargin: "Extra speed a drafting cop uses to close when farther back. Raise so it catches up faster.",
  maneuverTrigSpeed: "Player speed needed for an interceptor to start an overtake. Lower so it overtakes at lower speeds.",
  maneuverRange: "Distance within which a cop can start/own an overtake. Raise so it commits from further out.",
  maneuverBehind: "Distance a cop must be BEHIND you to start an overtake. Raise so only clearly-behind cops overtake.",
  maneuverCooldown: "Seconds after an overtake before that cop can run another. Raise to space out overtakes.",
  maneuverMaxTime: "Seconds an overtake runs before giving up. Raise to let it commit longer.",
  overtakeAhead: "Point ahead of you the overtaker sprints to. Raise so it tries to get further ahead.",
  overtakeSide: "Lateral swing so it passes AROUND you, not through. Raise if it rams your rear instead of passing (must clear ~23px envelope).",
  overtakeBoost: "Extra top speed while overtaking. Raise so it can actually pass a fast player.",
  overtakeDone: "Ahead distance at which overtake switches to block. Raise so it gets further ahead before brake-checking.",
  blockAhead: "Distance ahead a blocker sits to cut you off. Raise so it blocks from further ahead.",
  blockSpeedFactor: "Fraction of your speed a blocker eases to (brake-check). Lower for a harder brake-check.",
  blockMinSpeed: "Floor on a blocker's speed (won't dead-stop in front). Raise so it doesn't stall.",
  blockedSpeed: "Your speed below which a block 'succeeded' → handed to box/bust. Raise so blocks succeed more easily.",
  blockLost: "Along-distance below which a blocker has fallen behind (fail). More negative = it keeps trying longer.",
  boxTriggerSpeed: "Player speed below which a box forms. Raise to box you more readily.",
  boxReleaseSpeed: "Speed you must exceed to break a box. Lower to escape boxes more easily.",
  boxEngageRange: "Distance within which cops join a box. Raise so more cops pile into the sandwich.",
  boxCloseMargin: "Extra speed a rear boxer uses to close to contact. Raise so it closes onto you faster.",
  boxContactGap: "Gap (px) at which a rear boxer eases to your pace. Raise so it backs off contact sooner.",
  boxPress: "Speed a rear boxer presses ABOVE your pace to pin you forward (bounded). Raise to pin you harder.",
  boxFrontAhead: "Along distance a box cop must reach to count as 'in front' (then it blocks). Tuning for the front-runner handoff.",

  // ── PIT (rear-quarter push) ─────────────────────────────────────────────────
  pitMinLevel: "Lowest pursuit level a PIT may be attempted. Raise so PITs start later.",
  pitTestLevel: "Sandbox stand-in for the pursuit level (drives PIT force). Set to feel each level's PIT strength.",
  pitCooldown: "Seconds between PIT attempts across the WHOLE pack. Raise to make PITs rarer.",
  pitUnitCooldown: "Seconds before the same cop may PIT again. Raise to space out a single cop's PITs.",
  pitRange: "Distance within which a cop commits to a PIT. Raise so it commits from further out.",
  pitMinSpeed: "Min speed (you AND the cop) for a PIT. Raise so only fast chases get PITted.",
  pitMaxTime: "Seconds a PIT keeps pressing your rear quarter. Raise so it pushes longer.",
  pitGiveUp: "Seconds of lost rear-quarter contact before the PIT ends. Raise so it sticks through brief breaks.",
  pitBoost: "Extra top speed while committing to a PIT. Raise so it can press into your rear.",
  pitContactDist: "Centre distance at which the rear-quarter push registers. Raise to register from further out.",
  pitCoDirMin: "Min co-directional alignment (vs a head-on). Lower to allow PITs at sharper angles.",
  pitRearMax: "How far ahead of your centre the attacker may be and still PIT. Tuning for rear-bias.",
  pitSideMin: "Inner edge of the lateral band that counts as your rear QUARTER. Lower to PIT from more dead-behind.",
  pitSideMax: "Outer edge of the rear-quarter band. Raise to PIT from further out to the side.",
  pitRefSpeed: "Attacker speed counted as a full-force push. Lower so slower cops still push at full force.",
  pitPowerFloor: "Push-force multiplier at the lowest enabled level. Raise so low-level PITs push harder.",
  pitYawRate: "Yaw force (rad/s) at full strength — compare to your ~0.95 high-speed turn. Raise to overwhelm your countersteer.",

  // ── Spike unit / strips ─────────────────────────────────────────────────────
  spikeTrigSpeed: "Player speed needed to START a spike run. Lower so it triggers at lower speeds.",
  spikeDeployMinSpeed: "If you slow below this mid-run, the spike run aborts (spikes are for a moving target). ",
  spikeRange: "Distance within which a spike unit starts a run. Raise so it commits from further.",
  spikeBehind: "Distance it must be behind you to start the sprint. Raise so only clearly-behind units run.",
  spikeAhead: "Forward lead (ahead of the COP) it aims while sprinting past. Raise for a flatter, more committed pass.",
  spikeSide: "Lateral swing while sprinting (must clear the ~23px envelope or it shoves you). Raise if it leans on you instead of passing.",
  spikeBoost: "Sprint speed boost so it can pull ahead of you. Raise if it can't get clear to deploy.",
  spikeDropAhead: "How far ahead it must get before dropping the strip. Raise so the strip lands further in front (more dodge time).",
  spikeGlobalCooldown: "Seconds between ANY spike deploy across the whole pack. Raise so strips can't carpet the road — one strip, then a pack-wide wait.",
  spikeCloseFactor: "Speed cap while closing in (fraction of your speed). Lower so the spike unit hangs back longer before brake-checking; raise to close in faster.",
  spikeCloseBuffer: "Extra distance beyond blockAhead at which the unit switches from closing in to brake-checking. Raise to start the brake-check from further ahead.",
  spikeStripLen: "Width (px) of a cop-deployed spike strip (≈ car width = dodgeable). Raise to make it harder to dodge.",
  spikeProgressEps: "Forward gain (px) that counts as real progress in the sprint. Higher ignores jitter; lower = stricter.",
  spikeStallTime: "Seconds of NO progress before the sprint gives up. Raise so it persists while slowly winning the overtake.",
  spikeDeployHold: "Seconds it holds in front after dropping, if you don't pass. Raise to block you longer post-drop.",
  spikeDropCd: "Seconds between drops for one unit. Raise to space out strips.",
  spikeReload: "Seconds to reload after a unit empties its strip count. Raise for a longer dry spell.",
  spikeStripCount: "Strips a unit carries before reloading. Raise so it drops more before reloading.",
  spikeEaseAhead: "Distance ahead the deployer eases to after dropping. Tuning for the forward-block.",
  spikeEaseFactor: "Fraction of your speed it eases to after dropping (so the pack catches up). Lower to slow you harder.",
  spikeLeadDist: "Aim distance ahead of itself while LEADING (keeps it driving forward). Raise for a longer lead.",
  spikeLifetime: "Seconds a dropped strip persists. Raise to leave strips on the road longer.",
  spikeSpawnAhead: "Distance ahead a spike unit spawns. Raise so it appears further in front of you.",
  spikeEntrySpeed: "Speed it's already rolling at on spawn. Raise so it enters faster.",
  spikeRespawnDropCd: "Seconds after spawning before it can deploy (your window to ditch). Raise to give more warning.",

  // ── Gadget: Oil Slick ───────────────────────────────────────────────────────
  oilMaxCharges: "How many oil slicks you carry per run. (Changing this refills you.) Raise for more drops before you're empty.",
  oilPatchRadius: "Radius (px) of the oil patch (~1.5× car width by default). Raise to make a wider patch that's harder for a cop to thread around.",
  oilLifetime: "Seconds the patch stays on the road before fading out. Raise to leave the hazard down longer.",
  oilGripLost: "How hard oil makes a cop COAST — ignoring throttle, brakes AND steering, just carrying its momentum (the body still turns, but travel is locked). 1 = full ice (no control at all: slides straight until it hits a wall or the effect ends), 0 = no effect. Full strength for the whole effect duration, then off.",
  oilSpeedLost: "Fraction of a cop's speed scrubbed the instant it touches oil. 0 = no slow, 1 = dead stop. Raise to make the hit slow them more.",
  oilEffectTime: "Seconds the slide lasts (at full strength) after a cop leaves the patch, then it snaps back to normal. Raise to keep a cop sliding longer.",

  // ── Gadget: Smoke Screen ────────────────────────────────────────────────────
  smokeMaxCharges: "How many smoke clouds you carry per run. (Changing this refills you.) Raise for more drops before you're empty.",
  smokeRadius: "Cloud radius (px) once grown — this is ALSO the sight-block radius. Any cop sightline that passes within this of the cloud centre is blocked. Raise for a bigger screen that's harder to see around.",
  smokeLifetime: "Seconds the cloud blocks sight before it clears. Raise to keep cops blind longer (more time to ditch).",
  smokeGrowTime: "Seconds the cloud takes to expand from a tailpipe puff to full radius. Lower so it blocks sight almost instantly; raise for a slower bloom.",
  smokeFadeTime: "Seconds the cloud visually fades out over at the end of its life. Visual only — it still blocks until lifetime ends. Raise for a softer dissipate.",
  smokeOpacity: "Peak draw opacity of the cloud (visual only — does not change the block). Lower if it obscures the road too much for you.",
  smokeDropOffset: "How far behind your car (px) the cloud spawns. Raise to drop it further back (between you and a tailing cop); lower to drop it closer under your tail.",

  // ── Stealth (Kill Lights) ───────────────────────────────────────────────────
  killLightsRange: "Clear-LOS spotting range (px) for a SLOW, lights-off player. Lower = cops lose a blacked-out crawling car from closer in (easier ditch).",
  illumSpeedRef: "Speed (px/s) at which lights-off gives NO stealth — a dark car this fast is seen as if lit. Lower so you must crawl to benefit; raise to stay stealthy at speed.",

  // ── Respawn-ahead / dispatch ────────────────────────────────────────────────
  respawnDist: "Distance you must out-run a non-chasing cop before it's 'lost' and relocated. Raise to relocate less eagerly.",
  respawnTime: "Seconds a cop must stay lost + off-screen before relocating. Raise to relocate less eagerly.",
  respawnCooldown: "Seconds before a just-respawned cop can respawn again (anti-thrash). Raise to space out respawns.",
  interceptAheadDist: "Distance ahead an interceptor/heavy spawns for its head-on. Raise to spawn further ahead.",
  interceptEntrySpeed: "Speed an ahead-spawned interceptor rolls in at (toward you). Raise for a faster closing head-on.",
  heavyRespawnCooldown: "Pack-wide gate: only one heavy respawns ahead per this many seconds. Raise so heavies come back less often.",

  // ── Cop AI driving (unit tune) ──────────────────────────────────────────────
  maxApproachSpeed: "Speed a cop drives on a straight (its AI target speed). Raise so it chases faster.",
  cornerMinSpeed: "Speed it carries through a 90° corner. Raise to corner faster (risk of clipping); lower for cleaner corners.",
  brakeDecel: "How hard the AI brakes when planning for a corner. Raise so it slows earlier/harder before turns.",
  arriveRadius: "Distance at which a cop counts a waypoint as reached. Raise so it cuts corners more.",
  senseDist: "How far ahead the AI looks for corners. Raise so it plans turns earlier.",
  directRange: "Point-blank range at which a cop drives straight at you regardless of sight. Raise to beeline from further.",
  chaseRange: "Range within which a cop beelines (with sight) vs solving a road route. Raise to beeline from further.",
  reactionTime: "Cop steering reaction lag (s). Lower to make it sharper/twitchier.",
  ramRange: "Range at which the AI aims to ram. Tuning for ram approach.",
  turnBrakeAngle: "Heading error that makes the AI brake for a turn. Lower so it brakes for gentler turns.",
  turnBrakeSpeed: "Speed it brakes down to for a sharp turn. Lower for slower, cleaner cornering.",
  capR: "This unit's capsule radius (≈ half its width) for the rotated-car collider. Raise to make it wider in collisions.",
  capHalfLen: "This unit's capsule half-length (front/rear circle offset). Raise to make it longer in collisions.",

  // ── Separation / Tier-1 rejoin (cop tuning) ─────────────────────────────────
  sepRadius: "Boids separation radius — how close cops get before pushing apart in their targeting. Raise to spread the pack.",
  sepStrength: "How strongly cops steer apart when crowded. Raise to spread them more.",
  rbStart: "Distance behind where the Tier-1 rejoin blend BEGINS (a far cop drives more kinematically). Tuning for catch-up.",
  rbFull: "Distance behind where the rejoin blend is FULL (near-kinematic). Tuning for catch-up.",
  rbGrip: "Grip a far cop blends toward (higher = it stops washing wide). Raise to plant lagging cops.",
  rbTurnMult: "Turn-rate boost a far cop blends toward. Raise so lagging cops corner tighter to catch up.",
  rbSpeedBoost: "Top-speed boost a far cop blends toward. Raise so lagging cops catch up faster.",
};
